---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tekton-instana-version-resource-pipeline
spec:
  params:
    - name: branch
      type: string
      default: "main"
    - name: icr-username
      type: string
      default: "iamapikey"
    - name: icr-password
      type: string
      default: ""
  workspaces:
    - name: output
  tasks:
    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: output
      params:
        - name: url
          value: "https://github.com/instana/instana-version-resource.git"
        - name: revision
          value: $(params.branch)
        - name: deleteExisting
          value: "true"

    - name: build-instana-version-resource-image
      taskSpec:
        params:
          - name: cloned-dir
            type: string
            value: default
        steps:
          - name: build-instana-version-resource-image
            image: registry.access.redhat.com/ubi8/podman:latest
            script: |
              podman build -t instana-version-resource:latest $(params.cloned-dir)
              podman save -o /workspace/output/instana-version-resource.tar instana-version-resource:latest
        workspaces:
          - name: output
      runAfter:
        - git-clone
      params:
        - name: cloned-dir
          value: default

    - name: publish-instana-version-resource-image
      taskSpec:
        params:
          - name: image-tar
            type: string
            default: "/workspace/output/instana-version-resource.tar"
        steps:
          - name: publish-instana-version-resource-image
            image: registry.access.redhat.com/ubi8/podman:latest
            script: |
              podman load -i $(params.image-tar)
              podman tag instana-version-resource:latest icr.io/instana/instana-version-resource:latest
              podman login icr.io -u $(params.icr-username) -p $(params.icr-password)
              podman push icr.io/instana/instana-version-resource:latest
        workspaces:
          - name: output
      runAfter:
        - build-instana-version-resource-image
      params:
        - name: image-tar
          value: /workspace/output/instana-version-resource.tar
